gitignore: true

config:
  default: true # Enable all rules by default

  # false == RULE OFF
  MD013: false  # enforce a maximum line length
  MD024: false  # forbid duplicate heading content
  MD033: false  # forbid inline HTML
  MD034: false  # forbid bare URLs
  MD041: false  # require first line to be H1 heading
  MD046: false  # enforce a consistent code block style

  MD060:        # enforce a consistent table column style
    style: compact  # single space around cell content
